steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'firebase', '-f', 'firebase.Dockerfile', '.' ]
- name: node
  entrypoint: npm
  args: ['install', '--production', '--silent']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gsutil'
  args:
    - cp
    - gs://env-config.30emeciel.fr/live-web.env
    - .env.production
- name: node
  entrypoint: npm
  args: ['run', 'build']
  env:
    - 'REACT_APP_VERSION=$TAG_NAME build $SHORT_SHA'
- name: firebase
  args: ['deploy',  '--only=hosting']
